site_name: Eltex
nav:
  - Руководство по установке:
    - ig/index.md
    - ig/mkdocs_installation.md
    - Создание репозитория:
      - ig/repo_creation_gh.md
      - ig/repo_creation_gl.md
  - Руководство администратора:
    - ag/index.md
    - ag/setup.md
    - ag/pub_setup.md
theme:
  name: material
  logo: assets/Eltex.png
  favicon: assets/logo_fav.png
  custom_dir: overrides
  language: ru
  plugins:
  - search:
      lang: 
        - en
        - ru
  features:
    - navigation.instant # ускорение загрузки (SPA)
    - navigation.tracking # динамический URL страницы 
    - navigation.tabs # перенос названий документов в горизонтальное меню
    - navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
    - navigation.indexes # главные страницы разделов не отображаются в меню
    - navigation.top # вкл. кнопку возврата наверх
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Ночь
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: День
extra:
  version:
    provider: mike
